/* Author: Logan Lupeamanu (LoganLupeamanu@my.unt.edu)
 * Date: 10/16/2020
 * Instructor: Dr. Shrestha
 * Description: User attempts to guess a seeded random number 1-100
 */


#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;

//returns a seeded random number from 1-100 inclusive
int getRandom(){
    //generate a seeded random number
    //between 1 and 100, inclusive
    //return the random number
    srand(time(NULL));
    return (rand() % 100 + 1);
}

//compares the user's guess to a number generated by getRandom()
void compare(int guess){
    //call getRandom()
    //compare guess with the returned random number
    //inform user what the random number was
    //and whether it was greated than, or less than or equal to guess
    int num = getRandom();
    if(guess > num){
        cout << "Your guess (" << guess << ") was greater than the target (" << num << ")." << endl;
    }else if(guess < num){
        cout << "Your guess (" << guess << ") was less than the target (" << num << ")." << endl;
    }else{
        cout << "You guessed right! The number was " << num << endl;
    }
}

int main(){
    int guess;
    //get the value of guess from the user
    //call compare and pass guess as parameter
    cout << "Enter guess (1-100): "; cin >> guess;
    compare(guess);
    return 0;
}
